config/routes.rb
Rails.application.routes.draw do
	root 'customers#home'
	get '/pb_send', to: 'customers#pb_send'
	get '/non_pb_send', to: 'customers#non_pb_send'
	get '/dais_send', to: 'customers#dais_send'
  	get :pb, to: 'customers#pb', as: :pb
  	get :non_pb, to: 'customers#non_pb', as: :non_pb
  	get :dais, to: 'customers#dais', as: :dais
end

app/models/summit.rb
class Summit < ActiveRecord::Base
  include SummitQueries

  def self.generate_csvs
    dais_records  = Summit.execute_sp_dais
    pb_records    = Summit.execute_sp_pb
    sum_records   = Summit.execute_sp_sum

    sum_file      = "#{Rails.root}/public/sum_esp.csv"
    pb_file       = "#{Rails.root}/public/pb_esp.csv"
    dais_file     = "#{Rails.root}/public/dais_esp.csv"

    write_to_csv(sum_file, sum_records)
    write_to_csv(pb_file, pb_records)
    write_to_csv(dais_file, dais_records)

  end

  private

  def self.write_to_csv(file, records)
    CSV.open(file, 'w+') do |csv|
      records.each do |r|
        csv << [r.attributes['Email'].strip] #strip removes unncessary whitespace from each record
      end
    end
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/summit_queries.rb
module SummitQueries
  extend ActiveSupport::Concern

  included do
    establish_connection(
      :adapter  => ENV["SQL_SERVER"],
      :host     => ENV["IP"],
      :username => ENV["UN"],
      :password => ENV["PW"],
      :timeout => 90000
    )
  end

    module ClassMethods

      #this executes a stored procedure to return all ESP customers for Summit. About 20k records
      def execute_sp_sum
        return find_by_sql ["EXEC [OMNIA_ESUM_P_SUM_CM].[dbo].[zTony_SUM_SummitEBillNotification]"]
      end

      #this executes a stored procedure to return all ESP customers for Pelican Bay. About 4k records
      def execute_sp_pb
        find_by_sql ["EXEC [OMNIA_ESUM_P_SUM_CM].[dbo].[zTony_SUM_SummitEBillNotificationPelicanBay]"] 
      end

      #this executes a stored procedure to return all ESP customers for DAIS. About 1.3k records
      def execute_sp_dais
        find_by_sql ["EXEC [OMNIA_ESUM_P_SUMd_CM].[dbo].[zTony_SUM_DaisEBillNotification]"] 
      end

    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include CustomersHelper

  def home
  end

  def pb
    send_pb_email("pb_esp.csv")
  end

  def non_pb
    send_summit_email("sum_esp.csv")
  end

  def dais
    send_dais_email("dais_esp.csv")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
  #pelican bay
  def send_pb_email(csv_file)
    CSV.foreach("#{Rails.root}/public/#{csv_file}") do |customer|
      UserNotifier.send_pb_email(customer).deliver_now
      puts "#{$.}, sent to #{customer}"
    end
  end

  #summit
  def send_summit_email(csv_file)
    CSV.foreach("#{Rails.root}/public/#{csv_file}") do |customer|
      UserNotifier.send_non_pb_email(customer).deliver_now
      puts "#{$.}, sent to #{customer}"
    end
  end

  #dais
  def send_dais_email(csv_file)
    CSV.foreach("#{Rails.root}/public/#{csv_file}") do |customer|
      UserNotifier.send_dais_email(customer).deliver_now
      puts "#{$.}, sent to #{customer}"
    end
  end

  #irmaupdate
  def send_irma_email(csv_file)
    CSV.foreach("#{Rails.root}/public/#{csv_file}") do |customer|
      UserNotifier.send_irma_email(customer).deliver_now
      puts "#{$.}, sent to #{customer}"
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end
end

app/views/customers/dais.html.erb
<p>Emails were successfully sent to DAIS Customers</p>

app/views/customers/dais_send.html.erb
<%= link_to "Send Billing Notification to DAIS Customers", :controller => "customers", :action => "dais" %>

app/views/customers/home.html.erb
<h4>Navigate to one of the following links</h4>
<%= link_to "AOL Pelican Bay Customers", pb_send_url %>
<br>
<%= link_to "AOL Non-Pelican Bay Customers", non_pb_send_url %>
<br>
<%= link_to "DAIS Customers", dais_send_url %>

app/views/customers/non_pb.html.erb
<p>Emails were successfully sent to AOL Non-Pelican Bay Customers</p>

app/views/customers/non_pb_send.html.erb
<%= link_to "Send Billing Notification to Non-Pelican Bay Customers", :controller => "customers", :action => "non_pb" %>

app/views/customers/pb.html.erb
<p>Emails were successfully sent to AOL Pelican Bay Customers</p>

app/views/customers/pb_send.html.erb
<%= link_to "Send Billing Notification to Pelican Bay Customers", :controller => "customers", :action => "pb" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AOLSg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_notifier/send_dais_email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
       <title>Untitled Document</title>
        <style type="text/css">
            body {
                font-family: Calibri, Verdana, Geneva, sans-serif;
                font-size: 14px;
            }
            .container {
                width: 600px;
            }
           
            .left-side, .right-side {
                width: 300px;
            }
            .left-side {
                float: left;
            }
            .right-side {
                float: right;
                margin-top: -18px;
            }
            .clear {
                clear: both;
            }
            .not-registered {
                background-color: #e0e1e2;
                border: thin solid #000;
                padding: 10px;
            }
        </style>
    </head>
 
    <body>
        <div class="container">
            <div class="left-side">
                <p>Dear CUSTOMER,</p>
                <p>
                    Your latest Dais monthly billing statement is now available online for you to review and pay.
                </p>
                <p>
                    Payment is due by <strong><%= Date.today.beginning_of_month + 19 %>.</strong>
                </p>
            </div>
            <div class="right-side">
                 <%= email_image_tag("dais-logo.jpg", size: "300x179") %>
            </div>
            <div class="clear"></div>
            <hr />
            <div id="click-here">                   
                <a clicktracking=off href="https://daisonlinebillpay.daistechnologies.com/esp/security/login?ReturnUrl=https%3a%2f%2fdaisonlinebillpay.daistechnologies.com%2fesp">Click here</a> to view and manage your account online. Once logged in,
                you will be able to view your current and past monthly billing statements, make a payment, view payment history, and more.
            </div>
            <p>
                Call us today to enroll in AutoPay, if you haven't already, and never worry about late fees.
            </p>       
            <div class="not-registered">
                <p>Not registered for Dais account management? <a clicktracking=off href="https://daisonlinebillpay.daistechnologies.com/esp/Registration">Click here</a> to register now!</p>
                <p><strong>Please Note:</strong> You must have your most recent invoice in order to register online.</p>
                <p>For any questions or concerns, please reply to this email or contact us at (800) 376-9715.</p>
                <p>Our customer service agents are available 24/7 and will be more than happy to assist you.</p>
            </div>
            <p class="other-payment-options">
                <strong><u>Other Payment Options:</u></strong>
                <p>
                    <strong>Phone: </strong> (800) 376-9715
                </p>
                <p>
                    <strong>Mail: </strong> DAIS, 4558 35th Street, Orlando FL 32811
                </p>
            </p>
        </div>
    </body>
</html>

app/views/user_notifier/send_irma_email.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
.BODY {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.NEWS {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.Table {
    background-color: #e0e1e2;
    border: thin solid #000;
}

ul{
    padding-left:20px;
    font-weight:bold;
    list-style-type:square!important;
}

li{
    display:block;
    text-decoration:none;
    padding-left:60px;
}
.email-header {
    margin-left: -653px !important;
}
</style>
</head>

<body>
<table width="200" border="0">
   <tr>
      <td height="554">
         <table width="600" border="0">
            <tr>
               <td width="290">
                  
               </td>
               <td width="300">
                    <span class="email-header"><%= email_image_tag("SBBLogoPantoneTaglineOL.jpg", size: "245x112") %></span>
               </td>
            </tr>
         </table>
         <table width="600"  border="0" cellpadding="0" cellspacing="0">
            <p class="BODY">Summit Broadband Customers,</p>
            <tr>
               <td width="307" class="BODY">
                  <p>        
                     Summit Broadband has activated our business continuity plan and is closely monitoring conditions associated with Hurricane Irma for any impact to our customers or our network. All preparations and precautions have been taken, and procedures put into place to maximize the ability of our company to respond in a timely manner to any effects from the hurricane. 
                  </p>
                  <p>
                      In addition, Summit Broadband’s network equipment, located on your premises, is protected by an Uninterruptible Power System (UPS). This UPS will provide approximately four hours of continued up-time for the network equipment should you lose commercial power to your site. <strong>As we strive to maintain continuous service during and after any impact from the storm, we ask that you do not disconnect this equipment from your site’s commercial power, or that in the event you leave your facility, you do not shut off commercial power.</strong> Either action would trigger the UPS to start and would prematurely drain the batteries, which would cause a service interruption to both your services and Summit Broadband’s network.  
                  </p>
                  <p>
                    We sincerely appreciate your help and support and remain committed to providing you the most robust network possible.
                  </p>
                  <p>
                      If you have any questions about Summit Broadband’s preparedness activity, please contact our Commercial Service Center (CSC) at 877-244-0242 or your Account Manager. 
                  </p>
                  <p>Thank you,</p>
                  <p>
                    Summit Broadband<br>
                    Commercial Services
                    </p>
               </td>
            </tr>
         </table>
      </td>
   </tr>
</table>
</body>
</html>

app/views/user_notifier/send_non_pb_email.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
.BODY {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.NEWS {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.Table {
    background-color: #e0e1e2;
    border: thin solid #000;
}

ul{
    padding-left:20px;
    font-weight:bold;
    list-style-type:square!important;
}

li{
    display:block;
    text-decoration:none;
    padding-left:60px;
}
</style>
</head>

<body>
<table width="200" border="0">
   <tr>
      <td height="554">
         <table width="600" border="0">
            <tr>
               <td width="290">
                  <p class="BODY">Dear <strong>CUSTOMER</strong>,</p>
                  <p class="BODY">Your latest Summit Broadband monthly billing statement is now available online for you to review and pay. 
                  </p>
                  <p class="BODY">Payment is due by <strong><%= Date.today.beginning_of_month + 19 %>.</strong></p>
               </td>
               <td width="300">
                    <%= email_image_tag("SBBLogoPantoneTaglineOL.jpg", size: "245x112") %>
               </td>
            </tr>
         </table>
         <table width="600"  border="0" cellpadding="0" cellspacing="0">
            <tr>
               <td width="307" class="BODY">
                  <p>        
                     <a clicktracking=off href="https://webcare.summit-broadband.com">Click here</a> to view and manage your account online.  Once logged in, you will be able to view your current and past monthly billing statements, make a payment, view payment history, and more. </br>
                  </p>
               </td>
            </tr>
         </table>
         <table width="600" height="119" border="0" cellpadding="0" cellspacing="0">
            <tr>
               <td width="290" class="BODY" style="float:left;">
                  Call us today to enroll in AutoPay if you haven't already and never worry about late fees or  writing a check again.
                  <br /><br />
                  <b><u>Other payment options:</u></b>
                  <ul style="margin-bottom:-0px;">&#8226; &nbsp; <u>Phone:</u></ul>
                  <li>Central Florida: (407) 996-8900</li>
                  <li>Southwest Florida: (239) 444-0400</li>
                  </ul>
                  <ul style="margin-bottom:-0px;">&#8226; &nbsp; <u>Mail:</u></ul>
                  <li>Summit Broadband</li>
                  <li>P.O. Box 10822</li>
                  <li>Naples, FL 34101-0822</li>
                  </ul>
               </td>
               <td width="297">
                <table width="297" style="margin-top:-40px; border:solid; border-color:#666; border-width:1px;">
                    <tr>
                        <td>
                  <table width="292" border="0" align="right" cellpadding="5" cellspacing="2" class="Table">
                     <tr>
                        <td>
                           <p class="NEWS">Not registered for Summit Broadband account management? <a clicktracking=off href="https://webcare.summit-broadband.com/esp/Registration">Click here </a>to register now!</p>
                           <p class="NEWS">For any questions or concerns, please reply to this email or contact us at (407) 996-8900 or (239) 444-0400. </p>
                           <p class="NEWS">Our customer service agents are available 24/7 and will be more than happy to assist you.</p>
                        </td>
                     </tr>
                  </table>
                  </td>
                  </tr>
                  </table>
              </td>
            </tr>
         </table>
         <!-- <img src="/images/Bg.png" alt="" width="600" height="99" />   -->
         <%= email_image_tag("Bg.png", size: "600x99") %>
      </td>
   </tr>
</table>
</body>
</html>

app/views/user_notifier/send_pb_email.html.erb
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<style type="text/css">
.BODY {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.NEWS {
    font-family: Calibri, Verdana, Geneva, sans-serif;
    font-size: 14px;
}
.Table {
    background-color: #e0e1e2;
    border: thin solid #000;
}

ul{
    padding-left:20px;
    font-weight:bold;
    list-style-type:square!important;
}

li{
    display:block;
    text-decoration:none;
    padding-left:60px;
}
</style>
</head>

<body>
<table width="200" border="0">
   <tr>
      <td height="554">
         <table width="600" border="0">
            <tr>
               <td width="290">
                  <p class="BODY">Dear <strong>CUSTOMER</strong>,</p>
                  <p class="BODY">Your latest Summit Broadband monthly billing statement is now available online for you to review and pay. 
                  </p>
                  <p class="BODY">Payment is due by <strong><%= Date.today.beginning_of_month + 19 %>.</strong></p>
               </td>
               <td width="300">
                    <%= email_image_tag("SBBLogoPantoneTaglineOL.jpg", size: "245x112") %>
               </td>
            </tr>
         </table>
         <table width="600"  border="0" cellpadding="0" cellspacing="0">
            <tr>
               <td width="307" class="BODY">
                  <p>        
                     <a clicktracking=off href="https://webcare.summit-broadband.com">Click here</a> to view and manage your account online.  Once logged in, you will be able to view your current and past monthly billing statements, make a payment, view payment history, and more. </br>
                  </p>
               </td>
            </tr>
         </table>
         <table width="600" height="119" border="0" cellpadding="0" cellspacing="0">
            <tr>
               <td width="290" class="BODY" style="float:left;">
                  Call us today to enroll in AutoPay if you haven't already and never worry about late fees or  writing a check again.
                  <br /><br />
                  <b><u>Other payment options:</u></b>
                  <ul style="margin-bottom:-0px;">&#8226; &nbsp; <u>Phone:</u></ul>
                  <li>Pelican Bay: (239) 529-1500</li>
                  <li>Pelican Bay: (844) 220-5424</li>
                  </ul>
                  <ul style="margin-bottom:-0px;">&#8226; &nbsp; <u>Mail:</u></ul>
                  <li>Summit Broadband</li>
                  <li>P.O. Box 10822</li>
                  <li>Naples, FL 34101-0822</li>
                  </ul>
               </td>
               <td width="297">
                <table width="297" style="margin-top:-40px; border:solid; border-color:#666; border-width:1px;">
                    <tr>
                        <td>
                  <table width="292" border="0" align="right" cellpadding="5" cellspacing="2" class="Table">
                     <tr>
                        <td>
                           <p class="NEWS">Not registered for Summit Broadband account management?  <a clicktracking=off href="https://webcare.summit-broadband.com/esp/Registration">Click here </a>to register now!</p>
                           <p class="NEWS">For any questions or concerns, please reply to this email or contact us at (239) 529-1500 or (844) 220-5424. </p>
                           <p class="NEWS">Our customer service agents are available 24/7 and will be more than happy to assist you.</p>
                        </td>
                     </tr>
                  </table>
                  </td>
                  </tr>
                  </table>
              </td>
            </tr>
         </table>
         <%= email_image_tag("Bg.png", size: "600x99") %>
      </td>
   </tr>
</table>
</body>
</html>